name: sqlite3 build

# on:
#   push:
#     paths:
#     - '.github/workflows/ccpp.yml'

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'workflow start'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: download src 
      run: | 
        curl -O https://www.sqlite.org/2022/sqlite-amalgamation-3390400.zip
        unzip -j sqlite-amalgamation-3390400.zip -d sqlite
        cp CMakeLists.txt sqlite/

    - name: install cmake
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt update -y && sudo apt install cmake -y

    - name: build
      run: |
        cd sqlite
        cmake -B build . 
        cd build 
        cmake --build .
        mkdir -p release
        cp sqlite3 release

    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: release-linux
        path: sqlite/build/release

  build-windows:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2

    - name: install curl, unzip
      run: choco install curl unzip -y

    - name: download src 
      run: | 
        curl -O https://www.sqlite.org/2022/sqlite-amalgamation-3390400.zip
        unzip -j sqlite-amalgamation-3390400.zip -d sqlite
        copy CMakeLists.txt sqlite

    - name: build
      run: |
        cd sqlite
        cmake -B build . 
        cd build 
        cmake --build . --config Release

    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: release-windows
        path: sqlite/build/release
